app:
    app_name: "memory_tuner"
    app_logging_level: "INFO"

    ROOT_DIR: "memory_tuner"
    DATA_DIR: "data"

    EXECUTION_PATH: "build/db_runner_with_tuner"
    DATABASE_PATH: "/data"

lsm_tree_config:
  E: 1024         # 1KB bytes/entry
  M: 4294967296   # 4GB bytes  M: 21474836480  # 20GB
  # M: 104857600  # 100MB 单位:bytes 
  N: 10000000     # 初始化 entry 数量1000万条记录 ～ 10GB
  Q: 10000000     # 查询数量1000万 
  s: 4            # range query selectivity
  T: 10
  h: 5


# 输出路径
optimizer_path:
    memory_tuner_ckpt: "data/memory_tuner_ckpt.csv"
    memory_tuner_final: "data/memory_tuner_final.csv"
