app:
    app_name: "memory_tuner"
    app_logging_level: "INFO"

    ROOT_DIR: "memory_tuner"
    DATA_DIR: "data"

    EXECUTION_PATH: "build/db_runner_with_tuner"
    DATABASE_PATH: "/data"

output_path:
    main_exp_output: "data/memory_tuner/main_result.csv"

lsm_tree_config:
  E: 1024         # 1KB bytes/entry
  # M: 2147483648   # 2GB bytes
  M: 1073741824 # 1GB bytes
  N: 10000000      # 初始化entry数量1000万条记录 ～ 10GB
  Q: 100000000      # 查询数量10000万(1亿)
  s: 4            # range query selectivity
  T: 5
  h: 5
  B: 67108864 # initial_memory_buffer = 64MB

